### ISSUE TITLE
D3D sometimes fail to go to fullscreen

### ISSUE THREAD

**Issue by petschau** [petschau/WinFellow#48] opened 2019-06-10 19:29 UTC
Sometimes, fullscreen fails with this error message:
DXGI ERROR: IDXGIOutput::FindClosestMatchingMode: Refresh rate denominator should never be zero (unless numerator is zero). [ MISCELLANEOUS ERROR #71: ]

**Comment by carfesh** [comment] 2019-06-11 08:58
A similar issue which I can reproduce always; for me it says:

DXGI ERROR: IDXGIOutput::FindClosestMatchingMode: The display mode Scaling is not recognized. [ MISCELLANEOUS ERROR #74: ]

**Comment by carfesh** [comment] 2019-06-11 09:27
So in my case, the issue was fixed by this change: 1192d51fea5db7b100887ff7cbd6d92da1ab8775

It is an initialization that was in 0.5.7, but somehow got removed along the way. I don't know why it's necessary, as to me it seems like all properties are being set up, but in my case it made a difference.

**Comment by carfesh** [comment] 2019-06-11 18:39
I've just run a D3D fullscreen runtest over my OCS demo folder; for me the recent change worked fine for 145 cases, no problems initializing the screen and no crashes occurred.

**Comment by Speedvicio** [comment] 2019-06-11 19:23
Same problem here with the last compiled source

**Comment by carfesh** [comment] 2019-06-12 06:20
@Speedvicio Interesting, I had hoped that the change might fix Petter's issue as well. Just to make sure, could you try to reproduce your error from the Visual Studio debugger, with a debug build? Do you also get any DXGI errors shown in Visual Studio's output window, and if yes, which ones? How reliably are you able to reproduce it, does it feel random or does it always happen?

BTW: if you're interested in access to regular builds without the hazzle of compiling them yourself, you can gladly join our beta team, we're always happy to find interested new members! We have a DropBox where these are distributed. I would need your email address, and possibly your EAB handle, though. If you are interested, you can always drop me a mail at torsten.enderling@gmail.com.

**Comment by petschau** [comment] 2019-06-12 15:41
In my case, the problems also went away after Torstens fix.

**Comment by Speedvicio** [comment] 2019-06-12 15:49
are this change alligned with last source code?
I can test again tonight in debug mode by visual studio, i will report the error here.

**Comment by carfesh** [comment] 2019-06-12 16:19
My fix is already in the master branch, so downloading the current source code should contain it, yes. If you already checked out a Git working copy, maybe double-check that you update it to the latest version before you begin testing with it :-)

Debugging DXGI errors can be a bit tiresome, as not all of them can easily be captured into our logfile. On Windows 10, it may be necessary to execute the following command beforehand as an administrator, to install a component required for troubleshooting:

dism /online /add-capability /capabilityname:Tools.Graphics.DirectX~~~~0.0.1.0

If you can still reproduce the issue, it would be helpful if you could test this with a debug build of WinFellow started from within Visual Studio (I hope I'm translating it correctly, for me it's a green play icon with the text "local Windows-Debugger" besides it). You should let the error occur normally, quit WinFellow and let us know any DXGI errors that are shown in Visual Studio's output window. It may be buried between a lot of text, so you may need to scroll to find something.

Your fellow.log file from that session, as well as the config you used, might also be helpful. I still have the hope that you were using an outdated version of the source code, and that it is fixed for you as well.

Thanks in advance for your effort!

**Comment by carfesh** [comment] 2019-06-12 17:43
@Speedvicio: I've temporarily uploaded a debug build containing the latest change here: https://volafile.org/get/CXYms5lRbyahO/WinFellow_v0.5.8.1173-master-cdd9420-Debug.zip

If you want, you can also use that for testing. I've done some tests, you can also capture output using DebugView, a small tool by SysInternals (https://docs.microsoft.com/en-us/sysinternals/downloads/debugview).

It might be a nice alternative to using a full Visual Studio just to narrow down a graphics error.

**Comment by Speedvicio** [comment] 2019-06-12 20:26
Thanks for sharing debug precompiled version.
Fon unknown reason I can't compile anymore the last release, this is the error that appear on List errors:
Gravità	Codice	Descrizione	Progetto	File	Riga	Stato eliminazione
Errore	MSB3073	uscita dal comando "PowerShell.exe ..\Scripts\GitWCRev.ps1 -InputFileName ..\INCLUDE\versioninfo-wcrev.h -OutputFileName ..\INCLUDE\versioninfo.h
PowerShell.exe ..\Scripts\GitWCRev.ps1 -InputFileName ..\MSVC\GUI_versioninfo-wcrev.rc -OutputFileName ..\MSVC\GUI_versioninfo.rc
:VCEnd" con codice 1.	WinFellow	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v150\Microsoft.CppCommon.targets	128	

Anyway i have tested your compiled version and the error that appear when i swap from window mode to full screen do not appear anymore, tomorrow i can test also the x86 version on a old eeepc 70 netbook, except that it don't support dx11.
For debug by Visual studio, is not a problem for me to perform test, I used it every day.

**Comment by carfesh** [comment] 2019-06-13 07:10
> When you load a preset config file, both radiobuttons for Agnus blitter are checked.

Great catch, thanks - fixed in c6d6556.

Good to hear that the fix works for you as well. The error message above is usually displayed when the build process detects a change in the local working copy; it is an attempt to ensure that versioned builds are always created from clean sources.

Not sure what happened in your case, as the script should normally show a warning or an error message; I have adjusted the script further, it will now display a warning message if git is not found in the commandline, but will continue the build (so that it can be built directly from downloaded sources as well). I've also adjusted our README, as it didn't reflect that git and posh-git are usually required for building WinFellow.

**Closed by carfesh** 2019-06-13 07:10 UTC
Labels: bug

**Comment by Speedvicio** [comment] 2019-06-13 10:19
Today I have tested the debug version on another pc with win 10.
This time the app crash when swap from ddraw to dx.
This is the log captured by Dbgview, seem relative to missing D3D11 SDK Layers.
[fellow.LOG](https://github.com/petschau/WinFellow/files/3285421/fellow.LOG)

**Comment by carfesh** [comment] 2019-06-13 15:22
Yes, it seems to be missing the D3D debug layer; I believe the dism command above might take care of installing that; you could always test with a release build, the debug layer requirement is only an issue for debug builds.
